branches:
  except:
    - master
sudo: false
language: node_js
node_js:
  - '8.12.0'
before_script:
  - sudo apt-get update -y
  - sudo apt-get install pandoc libghc-pandoc-prof
  - pandoc -s ${TRAVIS_BRANCH}.docx -t markdown -o ${TRAVIS_BRANCH}.md
  - npm init -y
  - npm install textlint --save-dev
  - npm install textlint-rule-preset-ja-technical-writing --save-dev
  - npm install npx --save-dev
script:
  - npx textlint --preset ja-technical-writing ${TRAVIS_BRANCH}.md -f pretty-error
notifications:
  email: false
  slack:
    rooms:
      - secure: RDlQncIloLs3IIAlf46/7hWsSMdv/orAuCKa702Kjiz3WOsbXzMJku4mpjDkfSd3NRPdA2Q5LFt3rW+V5EVOaDqJclY0/j/eyI+nyigF59xEOFiFd4Lq+pYgDPcTHQW6xvyDjd4XGSQHvPiJHfdEZrJO243hGIPUFY34SOS7F76xdf1tO0HcEA/6rgNpn7nX+RP3ZGfIW6jmkcGnNcwqLuIXRqs0c4qAiszDKQrvDWW+v+zRtyRbocXSQ2ddJ47ChcN6vXgi+eI7qkHPXX+C+nc/oE11T01N455VPuwtQ9QW2Fo2nvaYRA4TAYN3VdZrC5CYnDLKLrrQwxHan7f4xNvri8bhXKKJbiCajoiC5lrV3qTyNM6h9LLQcgybse99pqpAqi/r12EXREfxlYUT2+A08/EC+msTMSGhp2RptS6tJnoaWSF8/UKa6CqT4397/O6m4ygFsWR7n+0ncC7qWOqbMeSFRSLQxULhLPv5l9LF6CssYsMP+PZr9i40VVB1BifOWlI+EUaba+BjQZ+GksqQhiu3etayYVfzjXUBk3JgqMSklYoKeD9iK3UNgDt+Xu9KxtbAKHwEmYo+KrNvKkKtaat61TAYVYama8Rg8T04HdC04osTf/kOUCMCP2cywrv91NLyolgYfjNwVUI2YCD8oj19X/8d/rokzL3t4JE=
    template:
      - "Sotsuron checked on `%{branch}`."
      - "Result: <https://travis-ci.org/github/ogi-iii/Sotsuron_CI/branches|%{message}>"
      - "----------------------------------------"
      - "Download Sotsuron: https://github.com/ogi-iii/Sotsuron_CI/raw/%{branch}/%{branch}.docx"