branches:
  except:
    - master
    - develop
sudo: false
language: node_js
node_js:
  - '8.12.0'
before_script:
  - sudo apt-get update -y
  - sudo apt-get install pandoc libghc-pandoc-prof
  - pandoc -s ${TRAVIS_BRANCH}.docx -t markdown -o ${TRAVIS_BRANCH}.md
  - npm init -y
  - npm install textlint --save-dev
  - npm install textlint-rule-preset-ja-technical-writing --save-dev
  - npm install npx --save-dev
script:
  - npx textlint --preset ja-technical-writing ${TRAVIS_BRANCH}.md -f pretty-error
notifications:
  email: false
  slack:
    rooms:
      - secure: "[API TOKEN]"
    template:
      - "'Sotsuron' updated: `%{branch}`."
      - "Document Checking Result: <https://travis-ci.org/github/ogi-iii/Sotsuron_CI/branches|%{message}>"
      - "----------------------------------------"
      - "File Download: https://github.com/ogi-iii/Sotsuron_CI/raw/%{branch}/%{branch}.docx"