sudo: false
language: python
python:
- '3.8'
before_script:
  - sudo apt-get update -y
  - sudo apt-get install nodejs npm pandoc
  - filename=basename *.docx .docx
  - python slack_notify.py ${filename}.docx
  - pandoc -s ${filename}.docx --wrap=none --reference-links --extract-media=media -t gfm --filter ./despan.py -o ${filename}.md
  - npm init -y
  - npm install textlint --save-dev
  - npm install textlint-rule-preset-ja-technical-writing --save-dev
  - npm install npx --save-dev
script:
  - npx textlint --preset ja-technical-writing ${filename}.md